global using NUnit.Framework;
global using FakeItEasy;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using ShopingList.Features.Products;
global using ShopingList.Features.ShopingLists;
global using ShopingList.Data.Models;
global using System.Security.Claims;